name: Lint, Format, and Type Check

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1

      - name: Install the project
        run: uv sync

      - name: Run ruff lint
        run: uv run ruff check .

      - name: Run ruff format
        run: uv run ruff format --check .