name: Lint, Format, and Type Check

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13.5"

      - name: Install the project
        run: uv sync --locked

      - name: Run ruff lint
        run: uv run ruff check .

      - name: Run ruff format
        run: uv run ruff format --check .