name: Lint, Format, and Type Check

on:
  push:
    # branches:
    #   - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/lint-and-type-check.yml'
  pull_request:
    # branches:
    #   - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/lint-and-type-check.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install the project
        run: uv sync --locked

      - name: Run mypy
        run: uv run mypy .

      - name: Run ruff lint
        run: uv run ruff check .

      - name: Run ruff format
        run: uv run ruff format --check .